"""
Model for generated Python code.

Defines a structured container for storing Python code produced by an LLM.
Ensures the code is directly executable and contains no explanations or metadata.
"""

from pydantic import BaseModel


class GeneratedCode(BaseModel):
    """
    Structured container for storing executable Python code generated by an LLM.

    This model is intended for use with LLMs producing structured output.
    It enforces that the `code` field contains only raw Python code:
    - No explanations, reasoning, or metadata.
    - Code must be directly executable with Python's `exec()`.

    Fields:
        code (str): The generated Python code as a string. Must contain
        only valid Python syntax, immediately executable, and free of
        any natural language content.
    """

    code: str
