"""
Agent state definition.

Defines the structure of the internal state used by the agent during
execution, including the question, data, tools, and debugging state.
"""

from typing import TypedDict, Annotated, List, Dict, Optional

from langchain_core.messages import AnyMessage
from langgraph.graph.message import add_messages


class AgentState(TypedDict):
    """
    TypedDict representing the agent's runtime state.

    Attributes:
        question (str): User question being processed.
        variables (Dict[str, any]): Mapping of file names to DataFrames or other variables.
        data_summaries (str): Summaries of the data available to the agent.
        dependencies (List[str]): Required packages or modules for code execution.
        tools (str): Description of tools available to the agent.
        agent_scratchpad (List[AnyMessage]): Messages generated during execution.
        visualization (Optional[str]): Optional visualization generated by the agent.
    """

    question: str
    variables: Dict[str, any]
    data_summaries: str
    dependencies: List[str]
    tools: str
    agent_scratchpad: Annotated[List[AnyMessage], add_messages]
    visualization: Optional[str]
